const menuData = [

  {
    id: 1,
    name: "Paneer Tikka",
    category: "Starters",
    price: 180,
    image: "https://www.themealdb.com/images/media/meals/58oia61564916529.jpg",
    description: "Grilled paneer cubes marinated in Indian spices and yogurt.",
  },
  {
    id: 2,
    name: "Veg Manchurian",
    category: "Starters",
    price: 160,
    image: "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg",
    description: "Crispy vegetable balls tossed in spicy garlic-soy sauce.",
  },
  {
    id: 3,
    name: "Hara Bhara Kebab",
    category: "Starters",
    price: 150,
    image: "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    description: "Spinach and green peas kebabs, shallow-fried to perfection.",
  },


  {
    id: 10,
    name: "Butter Chicken",
    category: "Main Course",
    price: 280,
    image: "https://www.themealdb.com/images/media/meals/uryqru1511798039.jpg",
    description: "Creamy tomato gravy with tender chicken pieces.",
  },
  {
    id: 11,
    name: "Paneer Butter Masala",
    category: "Main Course",
    price: 240,
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    description: "Paneer cubes cooked in rich buttery tomato curry.",
  },
  {
    id: 12,
    name: "Dal Makhani",
    category: "Main Course",
    price: 200,
    image: "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
    description: "Slow-cooked black lentils with butter and cream.",
  },

 
  {
    id: 20,
    name: "Chicken Biryani",
    category: "Biryani & Rice",
    price: 250,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Aromatic basmati rice cooked with spiced chicken.",
  },
  {
    id: 21,
    name: "Veg Biryani",
    category: "Biryani & Rice",
    price: 220,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Fragrant rice with mixed vegetables and Indian spices.",
  },
  {
    id: 22,
    name: "Jeera Rice",
    category: "Biryani & Rice",
    price: 120,
    image: "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
    description: "Flavored basmati rice tempered with cumin seeds.",
  },

  
  {
    id: 30,
    name: "Butter Naan",
    category: "Indian Breads",
    price: 40,
    image: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
    description: "Soft naan brushed with butter, baked in a tandoor.",
  },
  {
    id: 31,
    name: "Garlic Naan",
    category: "Indian Breads",
    price: 50,
    image: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
    description: "Naan infused with garlic and herbs, tandoor-baked.",
  },
  {
    id: 32,
    name: "Tandoori Roti",
    category: "Indian Breads",
    price: 30,
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    description: "Whole wheat bread roasted on clay tandoor.",
  },

  {
    id: 40,
    name: "Gulab Jamun",
    category: "Desserts",
    price: 90,
    image: "https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg",
    description: "Soft milk dumplings soaked in rose sugar syrup.",
  },
  {
    id: 41,
    name: "Rasmalai",
    category: "Desserts",
    price: 100,
    image: "https://www.themealdb.com/images/media/meals/7v3f5h1590485037.jpg",
    description: "Cottage cheese patties in creamy saffron milk.",
  },
  {
    id: 42,
    name: "Jalebi",
    category: "Desserts",
    price: 80,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Crispy, syrupy spiral sweet made from fermented batter.",
  },

  
  {
    id: 50,
    name: "Masala Chai",
    category: "Beverages",
    price: 60,
    image: "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
    description: "Traditional Indian spiced tea with milk.",
  },
  {
    id: 51,
    name: "Sweet Lassi",
    category: "Beverages",
    price: 70,
    image: "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
    description: "Refreshing yogurt drink with sugar and cardamom.",
  },
  {
    id: 52,
    name: "Cold Coffee",
    category: "Beverages",
    price: 120,
    image: "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
    description: "Iced coffee blended with milk and cream.",
  },
 
  {
    id: 60,
    name: "Chicken Tikka",
    category: "Starters",
    price: 200,
    image: "https://www.themealdb.com/images/media/meals/ypxvwv1511304979.jpg",
    description: "Spicy marinated chicken roasted in the tandoor.",
  },
  {
    id: 61,
    name: "Chilli Paneer",
    category: "Starters",
    price: 170,
    image: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    description: "Paneer cubes tossed in Indo-Chinese chilli sauce.",
  },
  {
    id: 62,
    name: "Fish Fry",
    category: "Starters",
    price: 220,
    image: "https://www.themealdb.com/images/media/meals/ttsvwy1511796715.jpg",
    description: "Crispy shallow-fried fish coated in masala.",
  },
  {
    id: 63,
    name: "Chicken 65",
    category: "Starters",
    price: 190,
    image: "https://www.themealdb.com/images/media/meals/yqwtvu1487426027.jpg",
    description: "Deep-fried spicy chicken bites from South India.",
  },
  {
    id: 64,
    name: "Veg Spring Roll",
    category: "Starters",
    price: 140,
    image: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    description: "Crispy rolls stuffed with seasoned veggies.",
  },
  {
    id: 65,
    name: "Mushroom Tikka",
    category: "Starters",
    price: 160,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Grilled mushrooms marinated in aromatic spices.",
  },


  {
    id: 70,
    name: "Mutton Rogan Josh",
    category: "Main Course",
    price: 340,
    image: "https://www.themealdb.com/images/media/meals/vxxvpt1511186191.jpg",
    description: "Kashmiri-style slow cooked mutton curry.",
  },
  {
    id: 71,
    name: "Kadai Paneer",
    category: "Main Course",
    price: 230,
    image: "https://www.themealdb.com/images/media/meals/uwxqwy1483384971.jpg",
    description: "Paneer cooked with capsicum in kadai masala.",
  },
  {
    id: 72,
    name: "Chicken Curry",
    category: "Main Course",
    price: 260,
    image: "https://www.themealdb.com/images/media/meals/1525876468.jpg",
    description: "Home-style chicken cooked with onions and spices.",
  },
  {
    id: 73,
    name: "Palak Paneer",
    category: "Main Course",
    price: 220,
    image: "https://www.themealdb.com/images/media/meals/wvqpwt1468256321.jpg",
    description: "Paneer cubes in smooth spinach gravy.",
  },
  {
    id: 74,
    name: "Aloo Gobi",
    category: "Main Course",
    price: 160,
    image: "https://www.themealdb.com/images/media/meals/uttrxw1511797945.jpg",
    description: "Potatoes and cauliflower sautéed with spices.",
  },
  {
    id: 75,
    name: "Chole Masala",
    category: "Main Course",
    price: 180,
    image: "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg",
    description: "Spicy chickpea curry cooked in Punjabi style.",
  },
  {
    id: 76,
    name: "Egg Curry",
    category: "Main Course",
    price: 150,
    image: "https://www.themealdb.com/images/media/meals/1550441882.jpg",
    description: "Boiled eggs simmered in rich tomato gravy.",
  },


  {
    id: 80,
    name: "Mutton Biryani",
    category: "Biryani & Rice",
    price: 320,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Slow-cooked rice layered with marinated mutton.",
  },
  {
    id: 81,
    name: "Egg Biryani",
    category: "Biryani & Rice",
    price: 190,
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    description: "Spiced biryani rice topped with boiled eggs.",
  },
  {
    id: 82,
    name: "Curd Rice",
    category: "Biryani & Rice",
    price: 110,
    image: "https://www.themealdb.com/images/media/meals/uttupv1511386448.jpg",
    description: "South Indian curd rice tempered with mustard.",
  },
  {
    id: 83,
    name: "Veg Fried Rice",
    category: "Biryani & Rice",
    price: 150,
    image: "https://www.themealdb.com/images/media/meals/1529446153.jpg",
    description: "Stir-fried rice tossed with vegetables.",
  },
  {
    id: 84,
    name: "Chicken Fried Rice",
    category: "Biryani & Rice",
    price: 180,
    image: "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg",
    description: "Chinese-style rice tossed with chicken.",
  },

 
  {
    id: 90,
    name: "Lachha Paratha",
    category: "Indian Breads",
    price: 40,
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    description: "Layered flaky paratha cooked with ghee.",
  },
  {
    id: 91,
    name: "Plain Roti",
    category: "Indian Breads",
    price: 15,
    image: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
    description: "Whole wheat flatbread cooked on tawa.",
  },
  {
    id: 92,
    name: "Kulcha",
    category: "Indian Breads",
    price: 35,
    image: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    description: "Soft leavened bread baked in a tandoor.",
  },

 
  {
    id: 100,
    name: "Kheer",
    category: "Desserts",
    price: 80,
    image: "https://www.themealdb.com/images/media/meals/uttupv1511386448.jpg",
    description: "Rice pudding flavored with cardamom.",
  },
  {
    id: 101,
    name: "Ice Cream Sundae",
    category: "Desserts",
    price: 120,
    image: "https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg",
    description: "Ice cream topped with nuts and syrup.",
  },
  {
    id: 102,
    name: "Gajar Halwa",
    category: "Desserts",
    price: 90,
    image: "https://www.themealdb.com/images/media/meals/7v3f5h1590485037.jpg",
    description: "Carrot pudding cooked with milk and ghee.",
  },

  
  {
    id: 110,
    name: "Lemon Soda",
    category: "Beverages",
    price: 40,
    image: "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
    description: "Sparkling lemon drink with sugar or salt.",
  },
  {
    id: 111,
    name: "Hot Coffee",
    category: "Beverages",
    price: 50,
    image: "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
    description: "Freshly brewed hot coffee with milk.",
  },
  {
    id: 112,
    name: "Badam Milk",
    category: "Beverages",
    price: 70,
    image: "https://www.themealdb.com/images/media/meals/yqwtvu1487426027.jpg",
    description: "Chilled milk flavored with almonds.",
  },

 
  {
    id: 120,
    name: "Masala Dosa",
    category: "South Indian",
    price: 120,
    image: "https://www.themealdb.com/images/media/meals/1529445878.jpg",
    description: "Crispy dosa filled with spicy potato masala.",
  },
  {
    id: 121,
    name: "Idli Sambar",
    category: "South Indian",
    price: 80,
    image: "https://www.themealdb.com/images/media/meals/1529446153.jpg",
    description: "Soft idlis served with hot sambar.",
  },
  {
    id: 122,
    name: "Vada Sambar",
    category: "South Indian",
    price: 90,
    image: "https://www.themealdb.com/images/media/meals/1529445878.jpg",
    description: "Crispy vadas paired with aromatic sambar.",
  },


  {
    id: 130,
    name: "Veg Hakka Noodles",
    category: "Chinese",
    price: 150,
    image: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    description: "Wok-tossed noodles with veggies.",
  },
  {
    id: 131,
    name: "Chicken Hakka Noodles",
    category: "Chinese",
    price: 180,
    image: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    description: "Noodles tossed with shredded chicken.",
  },
  {
    id: 132,
    name: "Schezwan Fried Rice",
    category: "Chinese",
    price: 160,
    image: "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg",
    description: "Spicy fried rice tossed in Schezwan sauce.",
  },

  
  {
    id: 140,
    name: "Samosa",
    category: "Starters",
    price: 20,
    image: "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg",
    description: "Crispy pastry filled with spiced potatoes.",
  },
  {
    id: 141,
    name: "Pav Bhaji",
    category: "Starters",
    price: 120,
    image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
    description: "Butter-toasted pav served with mashed vegetable curry.",
  },
  {
    id: 142,
    name: "Kachori",
    category: "Starters",
    price: 25,
    image: "https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg",
    description: "Flaky fried snack filled with spicy dal.",
  },


  {
    id: 150,
    name: "Thali Meal",
    category: "Main Course",
    price: 250,
    image: "https://www.themealdb.com/images/media/meals/vxxvpt1511186191.jpg",
    description: "Combination of curries, rice, roti and dessert.",
  },
  {
    id: 151,
    name: "Chicken Shawarma",
    category: "Main Course",
    price: 130,
    image: "https://www.themealdb.com/images/media/meals/ttsvwy1511796715.jpg",
    description: "Middle Eastern wrap stuffed with roasted chicken.",
  },
  {
    id: 152,
    name: "Grilled Sandwich",
    category: "Main Course",
    price: 90,
    image: "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    description: "Veg sandwich grilled with butter.",
  },
];

export default menuData;